site_name: Brahma Docs
theme:
  name: material
  logo: images/logo.png
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
  palette:
    - primary: blue grey
      scheme: default
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Brahma-fi
nav:
  - "index.md"
  - "ðŸ¤“ Research": "Research.md"
  - "Glossary.md"
  - "FAQ.md"
  - Products:
      - Aastra:
          - About: "Aastra.md"
          - "Aastra ETH-PUT": "AastraEthput.md"
          - "User Guide": "AastraUserGuide.md"
  - Developers:
      - "Deployed Contracts": "DeployedContracts.md"
      - "Architecture.md"
  - Governance:
      - "Brahma DAO": "BrahmaDAO.md"
      - "Governance and fund Control": "GovernanceAndFundControl.md"
  - Security:
      - "Self Audit": "SelfAudit.md"
      - "Test Approach and Methodology": "TestApproachAndMethodology.md"
      - "Contract Breakdown and Review": "ContractBreakdown.md"
      - "Research on similar protocol vulnerabilities": "ResearchOnSimilarProtocols.md"
      - "Security Reports for our Contracts": "SecurityReports.md"
  - "Additional Resources":
      - "Connect with us!": "Socials.md"
